# custom app config
# overrides DCAPE/apps/drone/dcape-app/docker-compose.yml

services:
  app:
    #labels:
      # # Uncomment this to have GRPC outside
      # - traefik.http.services.${APP_TAG}-grpc.loadbalancer.server.scheme=h2c
      # - traefik.http.services.${APP_TAG}-grpc.loadbalancer.server.port=8081
      # - traefik.http.routers.${APP_TAG}-grpc.rule=Host(`grpc.${APP_SITE}`)
      # - traefik.http.routers.${APP_TAG}-grpc.tls=${USE_TLS}
      # - traefik.http.routers.${APP_TAG}-grpc.tls.certresolver=default
      # - traefik.http.routers.${APP_TAG}-grpc.service=${APP_TAG}-grpc
    command:
      --as.my_url ${DCAPE_SCHEME}://${APP_SITE} --as.cookie_name showonce_token
    environment:
      - AS_TYPE
      - AS_HOST
      - AS_TEAM
      - AS_CLIENT_ID
      - AS_CLIENT_KEY
      - AS_COOKIE_SIGN_KEY
      - AS_COOKIE_CRYPT_KEY
